/* Add All Action constants here  */

const ACTION_TYPES = {
  // Splash Actions
  SPLASH_LAUNCHED: 'SPLASH_LAUNCHED',
  FETCH_PRICES: 'FETCH_PRICES',
  RECEIVE_PRICES: 'RECEIVE_PRICES',
  RECEIVE_ERROR: 'RECEIVE_ERROR',
  FETCH_ASSETS: 'FETCH_ASSETS',
  RECEIVE_ASSETS: 'RECEIVE_ASSETS',
  FETCH_ASSETPAIRS:'FETCH_ASSETPAIRS',
  RECEIVE_ASSETPAIRS: 'RECEIVE_ASSETPAIRS',
  SET_TRADE_SYMBOL: 'SET_TRADE_SYMBOL',
  FETCH_TRADES: 'FETCH_TRADES',
  RECEIVE_TRADES: 'RECEIVE_TRADES',
};

export { ACTION_TYPES };
