/* Add All Action constants here  */

const ACTION_TYPES = {
  // Splash Actions
  SPLASH_LAUNCHED: 'SPLASH_LAUNCHED',
  FETCH_PRICES: 'FETCH_PRICES',
  RECEIVE_PRICES: 'RECEIVE_PRICES',
  RECEIVE_ERROR: 'RECEIVE_ERROR'
};

export { ACTION_TYPES };
